### ISSUE TITLE
page-break-lines face missing

### ISSUE THREAD

**Issue by devx-opensource** [shouya/ancilla.el#1]
Hello,

Your package is missing the dependency https://github.com/purcell/page-break-lines. Not sure how it's useful for your library but I couldn't make it work without (Emacs 28, native comp, running in a  terminal)

BTW: interesting approach to use the text visible in the buffer as the context. I will test this approach and use the narrow emacs functions to see how it behaves.

**Comment by shouya** [comment]
Ah, my fault. I thought the face is built-in (otherwise I would simply enable `page-break-lines-mode`).

Thanks for pointing out, let me fix that.

**Comment by shouya** [comment]
the face should be fixed in decda0255a86b4f7377a4ffbf9ed34db727cb8e6, can you help confirm if it worked for you?

**Comment by devx-opensource** [comment]
Sorry for my late answer, it does work 👍
